name: futsmandu_design_system
description: Shared design system for Futsmandu apps
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
